/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author pc
 */
public class TextPanel extends javax.swing.JPanel {

    
    private static String useState = "none";
    private DBMS dbms;
    
    /*
     * Creates new form TextEntryPanel
     */
    public TextPanel() {
        initComponents();
        dbms = new DBMS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jTextPane1.setToolTipText("Enter commands");
        jTextPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EnterPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnterPressed
              
        if((evt.getKeyCode() == KeyEvent.VK_ENTER) && (evt.getID() == KeyEvent.KEY_PRESSED)) {
            String currentText = jTextPane1.getText();
            String lastLine = currentText.split("\n")
                    [currentText.split("\n").length-1];
            ArrayList<String[]> results = new ArrayList<>();
                    
            System.out.println("before use: " + useState);
            useState = QuaeryProcessor.useState(lastLine, useState);
            System.out.println("after use: " + useState);
            Object[] command = QuaeryProcessor.parse(lastLine);                                            
            
            //FIX use state issue            
            //REFACTOR create function for jTextPane.setText()
            switch((int)command[0]) {
                //clear  TESTED
                case 0:   
                    System.out.println("\nclear");
                    jTextPane1.setText(""); //FIX caret on second line                    
                    break;
                    
                //show dbs TESTED
                case 1:
                    System.out.println("\nshow dbs");
                    ArrayList<String> dbs = dbms.show_dbs();                    
                    for(int i=0; i<dbs.size(); i++) {
                        System.out.println(dbs.get(i));
                        try {
                            jTextPane1.getDocument().insertString(
                                    jTextPane1.getText().length(), 
                                    "\n".concat(dbs.get(i)), 
                                    null); 
                        } catch(Exception e) {}
                    }
                    break;
                    
                //use db_name    TESTED             
                case 2:
                    System.out.println("\nuse");
                    System.out.println(useState);
                    if(dbms.is_unique_name(useState)) {
                        System.out.println("TextPanel.create_database"); //have command that creates table
                        dbms.create_database(useState);
                    } else {
                        System.out.println("TextPanel.select_database");
                        //dbms.create_database(useState);                    
                    }
                    break;
                //db - show current database TESTED
                case 10:
                    System.out.println("\ndb");
                    if(!useState.equals("none")) 
                        jTextPane1.setText(useState + "\n");
                    else 
                        jTextPane1.setText("select database with use");
                    break;
                //show tables TESTED
                case 11:
                    System.out.println("\nshow tables");
                    if(!useState.equals("none")) {
                        ArrayList<String> tables = dbms.show_tables(useState);
                        for(int i=0; i<tables.size(); i++) {
                            try {
                                jTextPane1.getDocument().insertString(
                                    jTextPane1.getText().length(), 
                                    "\n".concat(tables.get(i)), 
                                    null); 
                            } catch(Exception e) {}                            
                        }  
                    } else {
                        try {
                            jTextPane1.getDocument().insertString(
                                    jTextPane1.getText().length(), 
                                    "\n".concat(lastLine.concat(" - select database")), 
                                    null);                        
                        } catch(Exception e) {}
                    }
                    break;
                //db.dropDatabase() TESTED               
                case 12:
                    System.out.println("\ndropDatabase");
                    if(!useState.equals("none")) {
                        dbms.drop_database(useState);
                    } else {
                        try {
                            jTextPane1.getDocument().insertString(
                                    jTextPane1.getText().length(), 
                                    "\n".concat(lastLine.concat(" - select database")), 
                                    null);                        
                        } catch(Exception e) {}
                    }                    
                    break;
                //db.createTable(###)  TESTED            
                case 13:
                    System.out.println("\ncreateTable");
                    if(!useState.equals("none")) {
                        dbms.create_table(useState, (String)command[1]);
                    } else {
                        try {
                            jTextPane1.getDocument().insertString(
                                    jTextPane1.getText().length(), 
                                    "\n".concat(lastLine.concat(" - select database")), 
                                    null);                        
                        } catch(Exception e) {}
                    }                            
                    break;
                //db.save()    
                case 14:
                    System.out.println("\nsave");
                    if(!useState.equals("none")) {
                        dbms.save(useState);
                    } else {
                        try {
                            jTextPane1.getDocument().insertString(
                                    jTextPane1.getText().length(), 
                                    "\n".concat(lastLine.concat(" - select database")), 
                                    null);                        
                        } catch(Exception e) {}
                    }        
                    break;                    
                //db.###.drop()      TESTED            
                case 101:
                    System.out.println("\ndrop");
                    if(!useState.equals("none")) {
                        dbms.drop_table(useState, (String)command[1]);
                    } else {
                        try {
                            jTextPane1.getDocument().insertString(
                                    jTextPane1.getText().length(), 
                                    "\n".concat(lastLine.concat(" - select database")), 
                                    null);                        
                        } catch(Exception e) {}
                    }                            
                    break;
                //db.###.find()    
                case 102:
                    System.out.println("\nfind");
                    if(!useState.equals("none")) {
                        results.clear();
                        results = dbms.find(useState, (String)command[1]);
                    } else {
                        try {
                            jTextPane1.getDocument().insertString(
                                    jTextPane1.getText().length(), 
                                    "\n".concat(lastLine.concat(" - select database")), 
                                    null);                        
                        } catch(Exception e) {}
                    }                           
                    break;                    
                //db.###.find().limit(###)                   
                case 1001:
                    System.out.println("\nlimit");
                    if(!useState.equals("none")) {
                        results.clear();                    
                        results = dbms.limit(useState, (String)command[1], (int)command[2]);
                    } else {
                        try {
                            jTextPane1.getDocument().insertString(
                                    jTextPane1.getText().length(), 
                                    "\n".concat(lastLine.concat(" - select database")), 
                                    null);                        
                        } catch(Exception e) {}
                    }                    
                    break;
                //db.###.find().sort({key:[-1;1]})                 
                case 1002:
                    System.out.println("\nTextPanel.sort");
                    if(!useState.equals("none")) {
                        results.clear();                    
                        results = dbms.sort(useState, (String)command[1], (String)command[2], (int)command[3]);
                    } else {
                        try {
                            jTextPane1.getDocument().insertString(
                                    jTextPane1.getText().length(), 
                                    "\n".concat(lastLine.concat(" - select database")), 
                                    null);                        
                        } catch(Exception e) {}
                    }                                 
                    break;
                //db.###.find().skip(###)                
                case 1003:       
                    if(!useState.equals("none")) {
                        results.clear();
                        results = dbms.skip(useState, (String)command[1], (int)command[2]);
                    } else {
                        try {
                            jTextPane1.getDocument().insertString(
                                    jTextPane1.getText().length(), 
                                    "\n".concat(lastLine.concat(" - select database")), 
                                    null);                        
                        } catch(Exception e) {}
                    }                          
                    break;                    
                case 999:                
                    try {
                        jTextPane1.getDocument().insertString(
                                jTextPane1.getText().length(), 
                                "\n".concat(lastLine.concat(" is not defined")), 
                                null);
                    } catch(Exception e) {}
            }
        }            
    }//GEN-LAST:event_EnterPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
